scss_files: 'app/styles/**/*.scss'

linters:
  ColorVariable:
    enabled: false
  HexNotation:
    style: lowercase
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: true
    style: exclude_zero
  NameFormat:
    enabled: true
  NestingDepth:
    enabled: true
    max_depth: 5
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: true
    ignore_unspecified: true
    order:
      - display
      - position
      - top
      - right
      - bottom
      - left
      - float
      - clear
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - align-content
      - align-items
      - align-self
      - justify-content
      - order
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-style
      - border-width
      - border-color
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - color
      - background
      - background-color
      - background-image
      - background-position
      - background-repeat
      - background-size
      - font
      - font-family
      - font-size
      - font-weight
      - font-style
      - font-variant
      - letter-spacing
      - line-height
      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-shadow
      - text-transform
      - text-wrap
      - white-space
      - word-spacing
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: true
    max_depth: 4
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2]
  SingleLinePerSelector:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space_or_newline
  StringQuotes:
    enabled: true
    style: single_quotes
  VendorPrefix:
    enabled: true
    excluded_identifiers:
      - transition
      - keyframes
